# Generated by Django 3.1.4 on 2020-12-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Identity Key')),
                ('alias_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Alias Name')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=255, verbose_name='Identity Key')),
                ('alias_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Alias Name')),
                ('sample_value', models.BinaryField(null=True, verbose_name='Sample Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
