# Generated by Django 3.1.4 on 2020-12-13 15:11

from django.db import migrations, models
import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='Is Primary Sample'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_file',
            field=models.FileField(default=None, null=True, upload_to='sample/', verbose_name='Sample File'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_hash',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Sample File HMAC-SHA256'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='key',
            field=models.CharField(default=samples.models.build_identity, max_length=255, verbose_name='Identity Key'),
        ),
    ]
